appName: paymentservice
repoUser: alexkkk21
appReplicas: 1
containerPort: 50051
serviceType: ClusterIP
servicePort: 50051
containerEnvVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"
