appName: recommendationservice
repoUser: alexkkk21
appReplicas: 1
containerPort: 8080
serviceType: ClusterIP
servicePort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_PROFILER
    value: "1"
resourcesReqCpu: 100m
resourcesReqMem: 128Mi
resourcesLimCpu: 200m
resourcesLimMem: 256Mi
