appName: shippingservice
repoUser: alexkkk21
appReplicas: 1
containerPort: 50051
serviceType: ClusterIP
servicePort: 50051
containerEnvVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"
resourcesReqCpu: 100m
resourcesReqMem: 64Mi
resourcesLimCpu: 200m
resourcesLimMem: 128Mi
